

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace MyoGaming
{
    partial ref class FilerwPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtbox;
        private: ::Windows::UI::Xaml::Controls::Button^ btnW;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtblock;
        private: ::Windows::UI::Xaml::Controls::Button^ btnR;
    };
}

