

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "GamePage.xaml.h"




void ::MyoGaming::GamePage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///GamePage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///GamePage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Storyboard named 'EnterStoryboard'
    EnterStoryboard = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"EnterStoryboard"));
    // Get the Storyboard named 'ExitStoryboard'
    ExitStoryboard = safe_cast<::Windows::UI::Xaml::Media::Animation::Storyboard^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ExitStoryboard"));
    // Get the StackPanel named 'ctr_up'
    ctr_up = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ctr_up"));
    // Get the StackPanel named 'ctr_left'
    ctr_left = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ctr_left"));
    // Get the StackPanel named 'ctr_down'
    ctr_down = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ctr_down"));
    // Get the StackPanel named 'ctr_right'
    ctr_right = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ctr_right"));
    // Get the StackPanel named 'pnl_display'
    pnl_display = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pnl_display"));
    // Get the TextBlock named 'txt_life'
    txt_life = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"txt_life"));
    // Get the HyperlinkButton named 'btn_start'
    btn_start = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"btn_start"));
    // Get the TextBlock named 'txt_timer'
    txt_timer = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"txt_timer"));
    // Get the HyperlinkButton named 'btn_exit'
    btn_exit = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"btn_exit"));
    // Get the TextBlock named 'txt_rw'
    txt_rw = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"txt_rw"));
    // Get the TextBlock named 'txt_score'
    txt_score = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"txt_score"));
    // Get the Image named 'img_display'
    img_display = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"img_display"));
}

void ::MyoGaming::GamePage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::ctr_up_PointerEntered);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::ctr_left_PointerEntered);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::ctr_down_PointerEntered);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::ctr_right_PointerEntered);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->PointerEntered +=
            ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::MyoGaming::GamePage::*)(Platform::Object^, Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&GamePage::pnl_display_PointerEntered);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MyoGaming::GamePage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&GamePage::btn_start_Click);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MyoGaming::GamePage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&GamePage::btn_exit_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

