

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Animation {
                    ref class Storyboard;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class TextBlock;
                ref class HyperlinkButton;
                ref class Image;
            }
        }
    }
}

namespace MyoGaming
{
    partial ref class GamePage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ EnterStoryboard;
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ ExitStoryboard;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ctr_up;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ctr_left;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ctr_down;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ctr_right;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ pnl_display;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txt_life;
        private: ::Windows::UI::Xaml::Controls::HyperlinkButton^ btn_start;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txt_timer;
        private: ::Windows::UI::Xaml::Controls::HyperlinkButton^ btn_exit;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txt_rw;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txt_score;
        private: ::Windows::UI::Xaml::Controls::Image^ img_display;
    };
}

