

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "NewgamePage.xaml.h"




void ::MyoGaming::NewgamePage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///NewgamePage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///NewgamePage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the TextBlock named 'txt_title'
    txt_title = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"txt_title"));
    // Get the HyperlinkButton named 'btn_classic'
    btn_classic = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"btn_classic"));
    // Get the HyperlinkButton named 'btn_timelimited'
    btn_timelimited = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"btn_timelimited"));
    // Get the HyperlinkButton named 'btn_back'
    btn_back = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"btn_back"));
}

void ::MyoGaming::NewgamePage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MyoGaming::NewgamePage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&NewgamePage::btn_classic_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MyoGaming::NewgamePage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&NewgamePage::btn_timelimited_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MyoGaming::NewgamePage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&NewgamePage::btn_back_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

